### ISSUE TITLE
need a countdown till year 2025

### ISSUE THREAD

**Issue by Primeknight19** [addievo/GTAVICountdown#1]
title

**Comment by Primeknight19** [comment]
@addievo

**Comment by addievo** [comment]
On it

**Comment by addievo** [comment]
But I dont know the exact release date :(

**Comment by addievo** [comment]
@Primeknight19 
![image](https://github.com/addievo/GTAVICountdown/assets/38064122/2ec89618-3363-4b5c-b0d8-1dc5d44cb29f)

**Comment by Primeknight19** [comment]
noice
